dependencies {
    devOnlyNonPublishable "com.azanor.baubles:Baubles:1.7.10-1.0.1.10:deobf"
    implementation "thaumcraft_fixed:Thaumcraft:1.7.10-4.2.3.5:dev"
    devOnlyNonPublishable "com.github.GTNewHorizons:NotEnoughItems:2.8.101-GTNH:dev"
    compileOnly "MineTweaker3:MineTweaker3-MC1710-Main:1.7.10-3.0.11.23"
    shadowImplementation("net.glease:tc4recipelib:1.5.39:dev") {
        transitive = false
    }
}
